# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 461b144cb7383f9cb1fbf858f0b13b3b46728fde52afc3a39eb87308df1ad91d770c136c485790081d65e247c66b695e18d63837b53c689753039995b3d02ea6

test:
  secret_key_base: 5685aba62af033dcda5534fc4f7b3a3fb781698fe6b5c0e08dd8e5e6585316094df2e08332fd84e3429bfbb8d375804a627ad68fc943b3450eee779e47aa381c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
